POST http://localhost:8081/test/product-test
Content-Type: application/json

{
    "myID":"4206913",
    "myname": "T-Shirt Weiss",
    "myprice": "29.99",
    "mydesc": "Ist es ein Vogel? Ist es ein Flugzeug? Nein, es ist ein T-Shirt",
    "mychar": ["Weiss", "100% Baumwolle", "klassicher Rundhals ausschnitt", "Single-Jersey", "halbarm", "Made in Germany"],
    "myurl": "./../../../img/shirt_weiss.jpg"
}

###

GET http://localhost:8081/test/product-test
