POST http://localhost:5000/userCreateTask/createUserTask
Content-Type: application/json

{
    "myID":"Niklas@gmail.com",
    "myfname": "Mohrenkopf",
    "mylname": "Strobel",
    "mypasswd": "1234qwer"
}

###

GET http://localhost:5000/userCreateTask/getUser
